apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: nifi
spec:
  serviceName: nifi
  replicas: {{.replicas}}
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
        - name: nifi
          command: ["/bin/sh","-c"]
          args: ['sed -e "s/^search/& $(dnsdomainname)/" /etc/resolv.conf > /tmp/resolv.conf;cat /tmp/resolv.conf  > /etc/resolv.conf; cd /opt/nifi && ./start_nifi.sh']
          image: {{.image}}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 8081
            - containerPort: 8443
            - containerPort: 2882
            - containerPort: 2181
          env:
            - name: ZK_NODES_LIST
              # Requires zookeeper running
              value: "nifi-0.nifi.nifi.svc.cluster.local,nifi-1.nifi.nifi.svc.cluster.local,nifi-2.nifi.nifi.svc.cluster.local"
            - name: ZK_CLIENT_PORT
              value: 2181
            - name: IS_CLUSTER_NODE
              value: "yes"
            - name: BANNER_TEXT
              value: "Nifi Cluster"
